### ISSUE TITLE
Flexible Download script

### ISSUE THREAD

**Issue by gfairbro** [UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor#10]
To prove to us that you can get the data into R or Python, write a script that takes a URL and a local file path as command line arguments which downloads and writes the file to your laptop. Use the {docopt} R or docopt Python package to create the command line argument functionality. You are not required upload the data to your project repository.

Note - this script should live in an appropriately named sub-directory of your public GitHub.com repo.

**Comment by Luming-ubc** [comment]
I opened a pull request for an initial version of the down_load.py 
Please review :)

**Comment by gfairbro** [comment]
These are completed and pending a pull request

**Comment by gfairbro** [comment]
Pull Req Created
