### ISSUE TITLE
Test Reproduceability

### ISSUE THREAD

**Issue by gfairbro** [UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor#135]
Each team member will attempt to run the entire pipeline

**Comment by gfairbro** [comment]
I was able to run this completely in 5 minutes, including download of container

**Comment by GloriaWYY** [comment]
I was able to run this, `docker build` takes around 5 minutes, and `docker run` takes another 7 minutes.

**Comment by gfairbro** [comment]
@GloriaWYY did you just run it like this?
docker run --rm -it -v <FULL_LOCAL_PATH_TO_REPO>:/home/jovyan/ gfairbro/wine_quality_predictor make all
Shouldnt have been more than one step.

**Comment by GloriaWYY** [comment]
@gfairbro I did `$ docker build --tag wine_quality_predictor .`, and then `$ docker run --rm -it -v /$(pwd):/home/jovyan/ wine_quality_predictor make all`

So the `docker build` command is not needed actually?

**Comment by gfairbro** [comment]
Not needed. what the run command with gfairbro/wine_quality_predictor will do is download the container image (if it is not already present on your computer) from my repo and run it.

**Comment by GloriaWYY** [comment]
@gfairbro Oh, yeah, that's because you already published the image on your DockHub? So we don't need to build it from the Dockerfile

**Comment by gfairbro** [comment]
Yep you got it!

**Comment by gfairbro** [comment]
Reproduceable except docker issues with M1.
