### ISSUE TITLE
Address Feedback

### ISSUE THREAD

**Issue by gfairbro** [UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor#136]
Each group memeber will address one feedback item and edit the issue comment

**Comment by GloriaWYY** [comment]
I will address comment(s) coming from the 4th commentator (Kylemaj) on Contributing file.

**Comment by paradise1260** [comment]
I will address the first and the third comment from the first reviewer (manju-abhinandana).

**Comment by GloriaWYY** [comment]
**Comments from Kylemaj on CONTRIBUTING.md**
1. You may want to consider adding contact information to your CONTRIBUTING.md file. While it is clear who to contact about a code of conduct violation it was less apparent who to contact regarding contributions and support. As an external contributor my first inclination was to open an issue when I couldn't find contact info in the README or CONTRIBUTING files.
2. CONTRIBUTING file instructs contributors to make minor edits directly to the main branch through github. This make sense for the core team but may be a bit confusing in an outward facing document.

**Commit addressing the comments**
https://github.com/UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor/commit/9dc54f947b000ef3cc924db09d0b415a9d7396a6

- Contact information is added (email)
- Restructured the CONTRIBUTING.md a bit so that it works as public-facing document instead of only for the maintainer team

**Comment by gfairbro** [comment]
Will address gn385x Comment  2 and Vikiano Comment 5 (really the same fix).

**Comment by gfairbro** [comment]
Addressing concerns from gn385x and Vikiano:

gn385x
3. Regarding the final report in Jupyter book, it only showed “Summary” in the section to search the book (on the left side), which did not to reflect correctly and caused confusion.

Vikiano
5. It will be great if you can include the authors - names of the group members - in the report summary.

**Commit addressing the comments**
7405529ead6b01df4c60a4cc17b817c245e0cb12
We were able to figure out why jupyter book was behaving that way, added an index page that included our title, author and date information. This had the added bonus of including Summary in the RHS table of contents.

**Comment by paradise1260** [comment]
Comments from manju-abhinandana:
1. environment.yml file could be placed in the root of project. There are a few scripts under src which is not being used. Can it be moved to an archive folder?
2. EDA: I think it would good to mention how large the dataset is. Including this will help someone looking at the report assess how good the results are. The figure 1 showing the class imbalance of wine quality score can be under analysis section.

How I addressed the comments:
1. I added the environment.yml file to the root of the project. Also, I removed unnecessary files from src directory. commits: https://github.com/UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor/commit/698e791add9e15a47b180ec345971a26d6e9b667, https://github.com/UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor/commit/13767b692661ab5085bc27ea20accfd3a19e423b, https://github.com/UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor/commit/fc20795a0f8b854a7d7522cc618553a4b4704e33
2. I added the breakdown of the examples in the train and test data. Also, I moved the figure of class imbalance to analysis section. commit: https://github.com/UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor/commit/57d23b2b8799b07cbf043ad71c7d012946cf05da

**Comment by Luming-ubc** [comment]
Comments from manju-abhinandana:
7. The conclusion and limitations could be under a separate subheading.

Comments from Kylemaj:
3. It was a bit confusing for me that your final report was named report summary given that there is another file in the wine_quality_predictor_report with the exact same name. You may want to change the name of your report to something that clearly marks it as the full and final version.

How I addressed the comments:

1. We added two separate subheadings for conclusion and limitations. Commits: https://github.com/UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor/commit/1b6b91ad6cbe26bf3c35b3a790c708439ac68fbb

2. We added project name as our report title, and moved summary as the first section. Commits: https://github.com/UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor/commit/c79a016dd9e0cc0a0f5210b4c4b0810d04d328c4
The final report structure could be found [here](https://ubc-mds.github.io/DSCI_522_group09_Wine_Quality_Predictor/index.html)

**Comment by GloriaWYY** [comment]
Addressing TA's feedback on Milestone 2 release:

> You're using `try`, `except` everywhere instead of checking if a file exists when outputting (and maybe reading) the files. You could instead check if the file exists and create it if it doesn't. Using `try` `except` in production except for when dealing with 3rd party stuff is not a good practice.

Thank you for your suggestions. We decided to use `if` statement to check if a file exists before exporting it, and we adopts `for` loops to make our codes DRY. Changes can be seen in 2dee29a5c4941d463f0664748b65ac28a579ea51

**Comment by gfairbro** [comment]
Luming Completed the submission to the feedback repo today
