### ISSUE TITLE
Meeting Minutes Nov 17, 2021

### ISSUE THREAD

**Issue by paradise1260** [UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor#2]
Start: 2 pm
Finish: 3:50 pm
Present Members: Luming, Gabriel, Gloria, Paniz

1. We worked on our team work contract and decided the meeting time, working hours, division of work, collaboration and quality of work.
2. We decided that each team member should find 2 questions and datasets by tonight (Nov 17th). We will rank the datasets through Github issues and select one of them by tomorrow (Nov 18th).
3. We divided the work. There is another issue which includes the tasks of each member for the first milestone. We have to divide project proposal, script for downloading the data and EDAs among ourselves.

**Comment by gfairbro** [comment]
Thanks @paradise1260 for documenting these! Closing this issue.
