### ISSUE TITLE
README Intro & Analysis Plan

### ISSUE THREAD

**Issue by gfairbro** [UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor#20]
Make a plan of how you will analyze the data (report an estimate and confidence intervals? hypothesis test? classification with a decision tree?). Choose something you already learned how to do in another MDS course.

**Comment by GloriaWYY** [comment]
Initial draft done, pending modification based on EDA, license, references.

**Comment by gfairbro** [comment]
Reviewed and updated, added missing bits.
