### ISSUE TITLE
Analysis Figure identification

### ISSUE THREAD

**Issue by gfairbro** [UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor#21]
Discuss at least one exploratory data analysis (EDA) table and one exploratory data analysis figure you will create that makes sense for your research question, the data that you have, and the analysis you plan to do.

Also, Suggest how you would share the results of your analysis as one or more tables and/or figures.

**Comment by GloriaWYY** [comment]
Blueprint done in README.md.

**Comment by gfairbro** [comment]
I think this is complete between EDA and Readme
