### ISSUE TITLE
Build Environment

### ISSUE THREAD

**Issue by gfairbro** [UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor#36]
We should create a custom environment to capture our dependencies and generate a YAML file.

**Comment by Luming-ubc** [comment]
Is this for milestone2?

**Comment by gfairbro** [comment]
Yeah i assumed it would be part since we talked about it but i will move them to Milestone 3 for now.

**Comment by gfairbro** [comment]
Moving this back to M2, i have created this file and uploaded it. we can tweak if we discover dependencies.
