### ISSUE TITLE
Third script - Split EDA code and data figures out to a separate script

### ISSUE THREAD

**Issue by gfairbro** [UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor#38]

**Comment by GloriaWYY** [comment]
> A third script which creates exploratory data visualization(s) and table(s) that are useful to help the reader/consumer understand that dataset. This should take two arguments: a path/filename pointing to the data; a path/filename prefix where to write the figure to and what to call it (e.g., results/this_eda.png)

I assume we only create one script to generate all figures & tables from eda?

**Comment by GloriaWYY** [comment]
I'm already halfway on creating this script (if I am correct we only need one script which generates multiple .csv and .png)

**Comment by gfairbro** [comment]
This script takes the Cleaned unpreprocessed Train DF and input and creates the existing EDA graphs and table as output

input:
train_df.csv

outputs:
table_1_combined_dataset.csv
table_2_observations_count.csv
table_3_summary.csv
figure_1_class_imbalance.png
figure_2_red_and_white_quantities
figure_3_distribution_of_features

**Comment by GloriaWYY** [comment]
Done, PR #46
