### ISSUE TITLE
Meeting Agenda Nov 19, 2021 

### ISSUE THREAD

**Issue by paradise1260** [UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor#4]
1. Discussion about what we have done so far if needs be.
2. Deciding the assignees of these tasks: project proposal, EDAs, script for downloading the data, releasing and uploading the necessary files on Canvas.
3. Deciding the name of the repository

P.S. Please comment if I have missed any tasks for milestone 1.

**Comment by gfairbro** [comment]
Lets divide the remaining issues up with an eye to have them completed by EOD Friday
