### ISSUE TITLE
Convert README to dynamic Jupyter Book

### ISSUE THREAD

**Issue by gfairbro** [UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor#40]

**Comment by gfairbro** [comment]
Lets separate the README into sections as described in synchronous lecture 3

**Comment by Luming-ubc** [comment]
Is this for milestone 2? or for later?

**Comment by gfairbro** [comment]
Yeah i am just realizing this must be for later.

**Comment by gfairbro** [comment]
Cancelling this idea for now.
