### ISSUE TITLE
Second script  - preprocessing the data

### ISSUE THREAD

**Issue by paradise1260** [UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor#41]
A second script that reads the data from the first script and performs and data cleaning/pre-processing, transforming, and/or paritionting that needs to happen before exploratory data analysis or modeling takes place. This should take at least two arguments:

a path/filename pointing to the data to be read in

a path/filename pointing to where the cleaned/processed/transformed/paritioned data should live

**Comment by gfairbro** [comment]
This script should take the downloaded csv as input  and have 3 outputs: Cleaned but raw Train DF ,and Preprocessed Train DF and Test DF.

input:
winequality-red.csv
winequality-white.csv

outputs:
train_df.csv
test_df.csv
train_df_preprocessed.csv
test_df_preprocessed.csv

**Comment by GloriaWYY** [comment]
Done, PR #46
