### ISSUE TITLE
Fourth Script that performs ML and summarizes

### ISSUE THREAD

**Issue by gfairbro** [UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor#44]
This will likely be a result of our multi-model comparison, we can flesh this out more at the synchronous session.

A fourth script that reads the data from the second script, performs some statistical or machine learning analysis and summarizes the results as a figure(s) and a table(s). These should be written to files. This should take two arguments:

a path/filename pointing to the data

a path/filename prefix where to write the figure(s)/table(s) to and what to call it (e.g., results/this_analysis)

**Comment by gfairbro** [comment]
Takes Preprocessed TrainDF as input and outputs ML results and visualizations.

**Comment by gfairbro** [comment]
input:
train_df.csv
test_df.csv

output:
TBD:
multiple figures and tables

Models:
Logistic Regression
SVM (Linear? - needs feature importance)
Random Forest

**Comment by paradise1260** [comment]
Done!
