### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by gfairbro** [UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor#6]
In an attempt to create a safe, positive, productive, and happy community, many organizations and developers create a code of conduct for their projects. A code of conduct in a Data Science project informs others of social norms, acceptable behaviour and general etiquette. It is more outward facing than the team work contract discussed above. We recommend Project Include for a comprehensive guide to writing an effective Code of Conduct.

At minimum, we believe that a good/effective code of conduct should include:

A Statement on diversity and inclusivity

Details on expected, and unacceptable behaviour

A list of consequences for unacceptable behaviour

A procedure for reporting and dealing with unacceptable behaviour

**Comment by GloriaWYY** [comment]
Done and initiated a pull request.

**Comment by gfairbro** [comment]
This has been reviewed by the group and merged
