### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by gfairbro** [UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor#7]
It is a good practice to include information about how others can contribute to your project somewhere in your repository. This is typically done as a separate file in a repo called CONTRIBUTING.md. Here are some examples of this file:

Altair

dplyr

Atom editor (very comprehensive)

If you’re interested in this, here’s a quick guide to creating this file from GitHub, but in the meantime, you can use the following snippet as a template:

We welcome all contributions to this project! If you notice a bug, or have a feature request, please open up an issue here. If you’d like to contribute a feature or bug fix, you can fork our repo and submit a pull request. We will review pull requests within 7 days. All contributors must abide by our code of conduct.

Note - this document should live in the root of your public GitHub.com repo.

**Comment by Luming-ubc** [comment]
CONTRIBUTING.md is added into the root of the repo. 
(Only skeleton is included, project information needs to be updated once decided)

**Comment by gfairbro** [comment]
This has been merged
